# -*- coding: utf-8 -*-
"""Project104 - mean,median,mode

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12U_guwQQnqUAkz2uoaEjbmj8z5pC1fAM
"""

from google.colab import files
datatoload = files.upload()

from collections import Counter
import csv

#creating the list
with open('SOCR-HeightWeight.csv', newline = '') as f:
  reader = csv.reader(f)
  r = list(reader)
r.pop(0)
newData=[]
for d in range(len(r)):
  num = r[d][1]
  newData.append(float(num))

  #finding the mean
  n = len(newData)
  total = 0
  for x in newData:
    total += x
  mean = total/n
  print(str(mean))

  #finding the median
  newData.sort()
  if n%2 == 0:
    median1 = float(newData[n//2])
    median2 = float(newData[n//2-1])
    median = (median1 + median2)/2
  else:
    median = newData[n//2]
  print(str(median))

#finding the mode
data = Counter(newData)
mode_data_range = {"75-85":0, "85-95":0, "95-105":0, "105-115":0}
for height,occurence in data.items():
  if 75<float(height)<85:
    mode_data_range["75-85"]+= occurence
  elif 85<float(height)<95:
    mode_data_range["85-95"]+=occurence
  elif 95<float(height)<105:
    mode_data_range["95-105"]+=occurence
  elif 105<float(height)<115:
    mode_data_range["105-115"]+=occurence
modeRange,modeOccurence = 0,0
for range,occurence in mode_data_range.items():
  if occurence>modeOccurence:
    modeRange,modeOccurence = [int(range.split('-')[0]),int(range.split('-')[1])],occurence
mode = float((modeRange[0]+ modeRange[1])/2)
print(f"mode=>{mode:2f}")